"""
r_export.py
===========
Generate a self-contained R script for every Jarvis Scholar plot and stat
test, so a user can reproduce the exact same result in RStudio.

Each script: (1) auto-installs/loads any needed packages, (2) embeds the
user's own data as a data.frame, (3) runs the matching analysis / plot and
saves the figure. Base R is used wherever possible; well-known CRAN packages
otherwise. Columns are renamed to the tool's canonical names so the code
always lines up with the embedded data.
"""
from __future__ import annotations

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# data.frame serialisation
# ---------------------------------------------------------------------------
def _is_numeric(s: pd.Series) -> bool:
    nn = s.notna().sum()
    if nn == 0:
        return False
    return pd.to_numeric(s, errors="coerce").notna().sum() == nn


def _rnum(x):
    if pd.isna(x):
        return "NA"
    f = float(x)
    return str(int(f)) if f.is_integer() else repr(round(f, 6))


def _rstr(x):
    if pd.isna(x):
        return "NA"
    return '"' + str(x).replace("\\", "\\\\").replace('"', '\\"') + '"'


def canon_df(df: pd.DataFrame, spec) -> pd.DataFrame:
    """Rename the user's columns to the spec's canonical names (case-insensitive)."""
    lower = {c.strip().lower(): c for c in df.columns}
    ren = {}
    for col in getattr(spec, "columns", []):
        key = col.name.strip().lower()
        if key in lower:
            ren[lower[key]] = col.name
    return df.rename(columns=ren)


def df_to_r(df: pd.DataFrame, name: str = "df") -> str:
    cols = []
    for c in df.columns:
        s = df[c]
        if _is_numeric(s):
            vals = ", ".join(_rnum(v) for v in pd.to_numeric(s, errors="coerce"))
        else:
            vals = ", ".join(_rstr(v) for v in s)
        cols.append(f"  `{c}` = c({vals})")
    body = ",\n".join(cols)
    return f"{name} <- data.frame(\n{body},\n  stringsAsFactors = FALSE, check.names = FALSE\n)"


def _header(title: str, packages) -> str:
    lines = [
        f"# {title}",
        "# Auto-generated by Jarvis Scholar — reproduce this result in RStudio.",
        "# Your data is embedded below; open in RStudio and run the whole script.",
        "",
    ]
    if packages:
        pk = ", ".join(f'"{p}"' for p in packages)
        lines += [
            "# --- packages (auto-installed if missing) ---",
            f"pkgs <- c({pk})",
            "to_install <- pkgs[!pkgs %in% rownames(installed.packages())]",
            "if (length(to_install)) install.packages(to_install, repos='https://cloud.r-project.org')",
            "invisible(lapply(pkgs, library, character.only = TRUE))",
            "",
        ]
    return "\n".join(lines)


def _sub(code: str, mapping: dict) -> str:
    for k, v in mapping.items():
        code = code.replace("@" + k + "@", str(v))
    return code


# ===========================================================================
# STATISTICS — per-test R  (id -> (packages, code))
# code may contain @TOKENS@ substituted from params
# ===========================================================================
STAT_R = {
"descriptives": (["psych"], """
if ("Group" %in% names(df)) {
  print(describeBy(df$Value, group = df$Group, mat = TRUE))
} else {
  print(describe(df$Value))
  print(t.test(df$Value)$conf.int)   # 95% CI for the mean
}
"""),
"crosstab": ([], """
tab <- table(df$CatA, df$CatB)
print(addmargins(tab))
print(round(prop.table(tab, 1) * 100, 1))   # row percentages
"""),
"shapiro": ([], """
if ("Group" %in% names(df)) {
  by(df$Value, df$Group, shapiro.test)
} else {
  shapiro.test(df$Value)
}
"""),
"levene": (["car"], """
leveneTest(Value ~ factor(Group), data = df)
"""),
"ttest_ind": (["effsize"], """
print(t.test(Value ~ Group, data = df))          # Welch by default
print(cohen.d(Value ~ Group, data = df))          # effect size
"""),
"mann_whitney": (["rstatix"], """
print(wilcox.test(Value ~ Group, data = df, exact = FALSE))   # exact=FALSE avoids the 'ties' warning
print(wilcox_effsize(df, Value ~ Group))          # rank-biserial
"""),
"ttest_one": ([], """
t.test(df$Value, mu = @MU@)
"""),
"anova_oneway": ([], """
fit <- aov(Value ~ factor(Group), data = df)
print(summary(fit))
print(TukeyHSD(fit))
"""),
"welch_anova": ([], """
oneway.test(Value ~ factor(Group), data = df, var.equal = FALSE)
"""),
"kruskal": (["FSA"], """
print(kruskal.test(Value ~ factor(Group), data = df))
print(dunnTest(Value ~ factor(Group), data = df, method = "bonferroni"))
"""),
"ttest_paired": ([], """
t.test(df$Before, df$After, paired = TRUE)
"""),
"wilcoxon": ([], """
wilcox.test(df$Before, df$After, paired = TRUE, exact = FALSE)   # exact=FALSE avoids the 'ties' warning
"""),
"friedman": ([], """
df$Condition <- factor(df$Condition); df$Subject <- factor(df$Subject)
friedman.test(Value ~ Condition | Subject, data = df)
"""),
"chi_square": (["rcompanion"], """
tab <- table(df$CatA, df$CatB)
print(chisq.test(tab))
print(cramerV(tab))
"""),
"fisher": ([], """
fisher.test(table(df$CatA, df$CatB))
"""),
"riskratio": (["epitools"], """
tab <- table(df$Exposure, df$Outcome)
print(riskratio(tab))
print(oddsratio(tab))
"""),
"gof": ([], """
chisq.test(x = df$Observed, p = df$Expected / sum(df$Expected))
"""),
"correlation": ([], """
print(cor.test(df$X, df$Y, method = "pearson"))
print(cor.test(df$X, df$Y, method = "spearman", exact = FALSE))  # exact=FALSE avoids the 'ties' warning
print(cor.test(df$X, df$Y, method = "kendall", exact = FALSE))
"""),
"corr_matrix": (["Hmisc"], """
num <- df[sapply(df, is.numeric)]
print(round(cor(num, use = "complete.obs"), 3))
print(rcorr(as.matrix(num)))     # r and p-values
"""),
"linear_reg": (["car"], """
fit <- lm(Y ~ ., data = df)
print(summary(fit))
print(confint(fit))
if (ncol(df) > 2) print(vif(fit))   # multicollinearity
"""),
"logistic_reg": ([], """
fit <- glm(Y ~ ., data = df, family = binomial)
print(summary(fit))
print(exp(cbind(OddsRatio = coef(fit), confint(fit))))   # OR + 95% CI
"""),
"cronbach": (["psych"], """
alpha(df)
"""),
"icc": (["irr"], """
wide <- reshape(df, idvar = "Subject", timevar = "Rater", direction = "wide")
icc(wide[, -1], model = "twoway", type = "agreement", unit = "single")
"""),
"kappa": (["irr"], """
kappa2(df[, c("Rater1", "Rater2")])
"""),
"diagnostic": (["caret"], """
lv <- sort(unique(c(df$Actual, df$Predicted)))
pos <- if ("Pos" %in% lv) "Pos" else tail(lv, 1)
confusionMatrix(factor(df$Predicted, levels = lv),
                factor(df$Actual, levels = lv), positive = pos)
"""),
"roc_auc": (["pROC"], """
r <- roc(df$TrueLabel, df$Score)
print(auc(r))
print(ci.auc(r))
print(coords(r, "best", best.method = "youden"))
plot(r, main = "ROC curve")
"""),
"power_ttest": (["pwr"], """
# leave one argument NULL to solve for it
pwr.t.test(d = @D@, sig.level = @A@, power = @P@, type = "two.sample")
"""),
"bootstrap": (["boot"], """
set.seed(1)
b <- boot(df$Value, function(d, i) mean(d[i]), R = 5000)
print(b)
print(boot.ci(b, type = "bca"))
"""),
"permutation": (["coin"], """
df$Group <- factor(df$Group)
oneway_test(Value ~ Group, data = df, distribution = approximate(nresample = 10000))
"""),
}


def stat_r_script(spec, df=None, params=None) -> str:
    params = params or {}
    packages, code = STAT_R.get(spec.id, ([], "# (R script not available for this test)\n"))
    if spec.id == "ttest_one":
        code = _sub(code, {"MU": _rnum(params.get("Population mean (mu0)", 0))})
    if spec.id == "power_ttest":
        n = params.get("Sample size per group (0 = solve)", 0)
        d = params.get("Effect size (Cohen's d)", 0.5)
        a = params.get("Alpha", 0.05)
        pw = params.get("Desired power", 0.8)
        # solve for whichever the user left blank: n=0 -> solve n via NULL power kept
        if n and float(n) > 0:
            code = ("# solving for achieved power given n\n"
                    f"pwr.t.test(n = {_rnum(n)}, d = {_rnum(d)}, sig.level = {_rnum(a)}, "
                    'type = "two.sample")\n')
        else:
            code = _sub(code, {"D": _rnum(d), "A": _rnum(a), "P": _rnum(pw)})
    parts = [_header(f"Statistics — {spec.name}", packages)]
    if getattr(spec, "needs_data", True) and df is not None:
        parts.append(df_to_r(canon_df(df, spec)))
        parts.append("")
    parts.append(code.strip() + "\n")
    return "\n".join(parts)


# ===========================================================================
# PLOTS — per-plot R  (id -> (extra_packages, kind, code))
# kind: "gg"  -> code sets `p`; builder adds print(p)+ggsave
#       "base"-> builder wraps code in png()/dev.off()
#       "self"-> code handles its own output/printing
# ===========================================================================
PLOT_R = {
# --- 1. distribution ---
"histogram": ([], "gg", """
if ("Group" %in% names(df)) {
  p <- ggplot(df, aes(Value, fill = Group)) +
       geom_histogram(bins = 20, alpha = .6, position = "identity", color = "white")
} else {
  p <- ggplot(df, aes(Value)) + geom_histogram(bins = 20, fill = "#2563eb", color = "white")
}
p <- p + theme_minimal() + labs(title = "Histogram", y = "Frequency")
"""),
"kde": ([], "gg", """
p <- ggplot(df, aes(Value)) +
  { if ("Group" %in% names(df)) geom_density(aes(fill = Group), alpha = .4) else geom_density(fill = "#2563eb", alpha = .4) } +
  theme_minimal() + labs(title = "Density (KDE)", y = "Density")
"""),
"box": ([], "gg", """
p <- ggplot(df, aes(Group, Value, fill = Group)) + geom_boxplot(alpha = .7) +
  theme_minimal() + labs(title = "Box plot") + theme(legend.position = "none")
"""),
"violin": ([], "gg", """
p <- ggplot(df, aes(Group, Value, fill = Group)) + geom_violin(alpha = .6, trim = FALSE) +
  geom_boxplot(width = .1, alpha = .6) + theme_minimal() + theme(legend.position = "none") +
  labs(title = "Violin plot")
"""),
"raincloud": (["ggdist"], "gg", """
p <- ggplot(df, aes(Group, Value, fill = Group)) +
  stat_halfeye(adjust = .6, width = .5, justification = -.2) +
  geom_boxplot(width = .12, alpha = .5, outlier.shape = NA) +
  geom_jitter(width = .05, alpha = .5) +
  theme_minimal() + theme(legend.position = "none") + labs(title = "Raincloud plot")
"""),
"strip": ([], "gg", """
p <- ggplot(df, aes(Group, Value, color = Group)) + geom_jitter(width = .15, size = 2.5, alpha = .8) +
  theme_minimal() + theme(legend.position = "none") + labs(title = "Strip / jitter plot")
"""),
"ecdf": ([], "gg", """
p <- ggplot(df, aes(Value)) +
  { if ("Group" %in% names(df)) stat_ecdf(aes(color = Group), linewidth = 1) else stat_ecdf(linewidth = 1, color = "#2563eb") } +
  theme_minimal() + labs(title = "ECDF", y = "Cumulative proportion")
"""),
"qq": ([], "gg", """
p <- ggplot(df, aes(sample = Value)) + stat_qq(color = "#2563eb") + stat_qq_line(color = "#d8572a") +
  theme_minimal() + labs(title = "Q-Q plot", x = "Theoretical", y = "Sample")
"""),
"ridgeline": (["ggridges"], "gg", """
p <- ggplot(df, aes(x = Value, y = Group, fill = Group)) +
  geom_density_ridges(alpha = .7) + theme_minimal() + theme(legend.position = "none") +
  labs(title = "Ridgeline plot")
"""),
# --- 2. comparison ---
"bar": ([], "gg", """
p <- ggplot(df, aes(Category, Value, fill = Category)) + geom_col() +
  theme_minimal() + theme(legend.position = "none") + labs(title = "Bar chart")
"""),
"grouped_bar": ([], "gg", """
p <- ggplot(df, aes(Category, Value, fill = Group)) + geom_col(position = "dodge") +
  theme_minimal() + labs(title = "Grouped bar")
"""),
"stacked_bar": ([], "gg", """
p <- ggplot(df, aes(Category, Value, fill = Group)) + geom_col(position = "stack") +
  theme_minimal() + labs(title = "Stacked bar")
"""),
"pct_stacked_bar": ([], "gg", """
p <- ggplot(df, aes(Category, Value, fill = Group)) + geom_col(position = "fill") +
  scale_y_continuous(labels = scales::percent) + theme_minimal() + labs(title = "100% stacked bar", y = "Percent")
"""),
"hbar": ([], "gg", """
p <- ggplot(df, aes(reorder(Category, Value), Value, fill = Category)) + geom_col() + coord_flip() +
  theme_minimal() + theme(legend.position = "none") + labs(title = "Horizontal bar", x = "Category")
"""),
"errorbar": (["Hmisc"], "gg", """
p <- ggplot(df, aes(Group, Value)) +
  stat_summary(fun = mean, geom = "col", fill = "#2563eb", alpha = .8) +
  stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), geom = "errorbar", width = .2) +
  theme_minimal() + labs(title = "Mean +/- SD")
"""),
"lollipop": ([], "gg", """
p <- ggplot(df, aes(reorder(Category, Value), Value)) +
  geom_segment(aes(xend = Category, y = 0, yend = Value), color = "grey") +
  geom_point(size = 4, color = "#2563eb") + coord_flip() + theme_minimal() +
  labs(title = "Lollipop chart", x = "Category")
"""),
"dumbbell": ([], "gg", """
p <- ggplot(df) +
  geom_segment(aes(x = Before, xend = After, y = reorder(Category, After), yend = Category), color = "grey") +
  geom_point(aes(Before, Category), color = "#2563eb", size = 3) +
  geom_point(aes(After, Category), color = "#d8572a", size = 3) +
  theme_minimal() + labs(title = "Dumbbell plot", x = "Value", y = "Category")
"""),
"slope": ([], "gg", """
p <- ggplot(df, aes(Time, Value, group = Subject, color = Subject)) +
  geom_line(linewidth = 1) + geom_point(size = 2) + theme_minimal() + labs(title = "Slope / before-after")
"""),
"radar": (["fmsb", "reshape2"], "base", """
if ("Series" %in% names(df)) {
  w <- dcast(df, Series ~ Metric, value.var = "Value"); rownames(w) <- w$Series; w$Series <- NULL
} else {
  w <- dcast(df, . ~ Metric, value.var = "Value"); w[["."]] <- NULL
}
mx <- apply(w, 2, max); mn <- rep(0, ncol(w))
radarchart(rbind(mx, mn, w), title = "Radar chart")
"""),
"grouped_box": ([], "gg", """
p <- ggplot(df, aes(Group, Value, fill = Subgroup)) + geom_boxplot() +
  theme_minimal() + labs(title = "Grouped box plot")
"""),
# --- 3. relationship ---
"scatter": ([], "gg", """
p <- ggplot(df, aes(X, Y)) +
  { if ("Group" %in% names(df)) geom_point(aes(color = Group), size = 3, alpha = .8) else geom_point(size = 3, alpha = .8, color = "#2563eb") } +
  theme_minimal() + labs(title = "Scatter plot")
"""),
"scatter_reg": ([], "gg", """
r <- cor(df$X, df$Y)
p <- ggplot(df, aes(X, Y)) + geom_point(size = 3, alpha = .8, color = "#2563eb") +
  geom_smooth(method = "lm", se = TRUE, color = "#d8572a") +
  annotate("text", x = min(df$X), y = max(df$Y), hjust = 0, label = paste0("r = ", round(r, 3))) +
  theme_minimal() + labs(title = "Scatter + regression")
"""),
"bubble": ([], "gg", """
p <- ggplot(df, aes(X, Y, size = Size)) + geom_point(alpha = .55, color = "#7d3c98") +
  { if ("Label" %in% names(df)) geom_text(aes(label = Label), size = 3, vjust = -1) } +
  scale_size(range = c(3, 15)) + theme_minimal() + labs(title = "Bubble chart")
"""),
"corr_heatmap": (["ggcorrplot"], "gg", """
num <- df[sapply(df, is.numeric)]
p <- ggcorrplot(cor(num, use = "complete.obs"), lab = TRUE, colors = c("#2563eb", "white", "#d8572a")) +
  labs(title = "Correlation heatmap")
"""),
"pairplot": (["GGally"], "gg", """
if ("Group" %in% names(df)) {
  p <- ggpairs(df, aes(color = Group))
} else {
  p <- ggpairs(df[sapply(df, is.numeric)])
}
"""),
"density2d": ([], "gg", """
p <- ggplot(df, aes(X, Y)) + stat_density_2d(aes(fill = after_stat(level)), geom = "polygon") +
  geom_point(alpha = .3, size = .8) + theme_minimal() + labs(title = "2D density")
"""),
"hexbin": (["hexbin"], "gg", """
p <- ggplot(df, aes(X, Y)) + geom_hex(bins = 25) + scale_fill_gradient(low = "#dbe9fb", high = "#12283b") +
  theme_minimal() + labs(title = "Hexbin plot")
"""),
"connected_scatter": ([], "gg", """
df <- df[order(df$Order), ]
p <- ggplot(df, aes(X, Y)) + geom_path(color = "grey") + geom_point(size = 3, color = "#2563eb") +
  theme_minimal() + labs(title = "Connected scatter")
"""),
# --- 4. trends ---
"line": ([], "gg", """
if ("Series" %in% names(df)) {
  p <- ggplot(df, aes(factor(X), Y, color = Series, group = Series)) + geom_line(linewidth = 1) + geom_point()
} else {
  p <- ggplot(df, aes(factor(X), Y, group = 1)) + geom_line(linewidth = 1, color = "#2563eb") + geom_point()
}
p <- p + theme_minimal() + labs(title = "Line chart", x = "X")
"""),
"multiline": ([], "gg", """
p <- ggplot(df, aes(factor(X), Y, group = Series, color = Series)) + geom_line(linewidth = 1) + geom_point() +
  theme_minimal() + labs(title = "Multi-series line", x = "X")
"""),
"area": ([], "gg", """
df$xpos <- as.numeric(factor(df$X, levels = unique(df$X)))
p <- ggplot(df, aes(xpos, Y)) + geom_area(fill = "#2563eb", alpha = .4) + geom_line(color = "#2563eb") +
  scale_x_continuous(breaks = df$xpos, labels = df$X) + theme_minimal() + labs(title = "Area chart", x = "X")
"""),
"stacked_area": ([], "gg", """
df$xpos <- as.numeric(factor(df$X, levels = unique(df$X)))
p <- ggplot(df, aes(xpos, Value, fill = Series)) + geom_area(alpha = .85) +
  scale_x_continuous(breaks = unique(df$xpos), labels = unique(df$X)) +
  theme_minimal() + labs(title = "Stacked area", x = "X")
"""),
"step": ([], "gg", """
p <- ggplot(df, aes(X, Y)) + geom_step(color = "#2563eb", linewidth = 1) + geom_point() +
  theme_minimal() + labs(title = "Step plot")
"""),
"line_ci": ([], "gg", """
p <- ggplot(df, aes(X, Y)) + geom_ribbon(aes(ymin = Lower, ymax = Upper), fill = "#2563eb", alpha = .2) +
  geom_line(color = "#2563eb", linewidth = 1) + geom_point() + theme_minimal() + labs(title = "Line + CI band")
"""),
# --- 5. composition ---
"pie": ([], "gg", """
p <- ggplot(df, aes(x = "", y = Value, fill = Label)) + geom_col(width = 1, color = "white") +
  coord_polar("y") + theme_void() + labs(title = "Pie chart")
"""),
"donut": ([], "gg", """
p <- ggplot(df, aes(x = 2, y = Value, fill = Label)) + geom_col(width = 1, color = "white") +
  coord_polar("y") + xlim(.5, 2.5) + theme_void() + labs(title = "Donut chart")
"""),
"waffle": (["waffle"], "gg", """
v <- setNames(round(df$Value / sum(df$Value) * 100), df$Label)
p <- waffle(v, rows = 10, title = "Waffle chart")
"""),
"treemap": (["treemapify"], "gg", """
p <- ggplot(df, aes(area = Value, fill = Label, label = Label)) +
  geom_treemap() + geom_treemap_text(colour = "white", place = "centre") +
  theme(legend.position = "none") + labs(title = "Treemap")
"""),
"sunburst": (["plotly"], "self", """
parents <- unique(df$Parent)
lab <- c(parents, df$Label)
par <- c(rep("", length(parents)), df$Parent)
val <- c(sapply(parents, function(pp) sum(df$Value[df$Parent == pp])), df$Value)
fig <- plot_ly(labels = lab, parents = par, values = val, type = "sunburst", branchvalues = "total")
print(fig)   # opens in the RStudio Viewer
"""),
"sankey": (["ggalluvial"], "gg", """
p <- ggplot(df, aes(axis1 = Source, axis2 = Target, y = Value)) +
  geom_alluvium(aes(fill = Source)) + geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Source", "Target")) + theme_minimal() + labs(title = "Sankey / flow")
"""),
"mosaic": ([], "base", """
mosaicplot(xtabs(Value ~ CatA + CatB, data = df), main = "Mosaic plot", color = TRUE)
"""),
# --- 6. statistical / biomedical ---
"forest": ([], "gg", """
p <- ggplot(df, aes(Estimate, reorder(Study, Estimate))) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "#d8572a") +
  geom_errorbarh(aes(xmin = LowerCI, xmax = UpperCI), height = .2) +
  geom_point(size = 3, color = "#2563eb") + theme_minimal() + labs(title = "Forest plot", y = "Study")
"""),
"coef_plot": ([], "gg", """
p <- ggplot(df, aes(Estimate, reorder(Term, Estimate))) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "#d8572a") +
  geom_errorbarh(aes(xmin = LowerCI, xmax = UpperCI), height = .2) +
  geom_point(size = 3, color = "#2563eb") + theme_minimal() + labs(title = "Coefficient plot", y = "Term")
"""),
"funnel": ([], "gg", """
p <- ggplot(df, aes(Estimate, StdError)) + geom_point(size = 3, color = "#2563eb") +
  scale_y_reverse() + geom_vline(xintercept = mean(df$Estimate), color = "#d8572a") +
  theme_minimal() + labs(title = "Funnel plot")
"""),
"kaplan_meier": (["survival", "survminer"], "self", """
fit <- survfit(Surv(Time, Event) ~ Group, data = df)
g <- ggsurvplot(fit, data = df, pval = TRUE, risk.table = FALSE, title = "Kaplan-Meier")
print(g)
ggsave("jarvis_kaplan_meier.png", g$plot, width = 8, height = 5, dpi = 300)
"""),
"cuminc": (["survival", "survminer"], "self", """
fit <- survfit(Surv(Time, Event) ~ Group, data = df)
g <- ggsurvplot(fit, data = df, fun = "event", title = "Cumulative incidence")
print(g)
ggsave("jarvis_cuminc.png", g$plot, width = 8, height = 5, dpi = 300)
"""),
"roc": (["pROC"], "base", """
r <- roc(df$TrueLabel, df$Score)
plot(r, main = paste0("ROC (AUC = ", round(auc(r), 3), ")"))
"""),
"pr_curve": (["PRROC"], "base", """
pr <- pr.curve(scores.class0 = df$Score[df$TrueLabel == 1],
               scores.class1 = df$Score[df$TrueLabel == 0], curve = TRUE)
plot(pr)
"""),
"confusion": ([], "base", """
tab <- table(Predicted = df$Predicted, Actual = df$Actual)
fourfoldplot(tab, main = "Confusion matrix")
"""),
"calibration": ([], "gg", """
df$bin <- cut(df$Predicted, breaks = seq(0, 1, length.out = 6), include.lowest = TRUE)
agg <- aggregate(cbind(Predicted, Observed) ~ bin, df, mean)
p <- ggplot(agg, aes(Predicted, Observed)) + geom_abline(linetype = "dashed", color = "grey") +
  geom_line(color = "#2563eb") + geom_point(size = 3, color = "#2563eb") +
  xlim(0, 1) + ylim(0, 1) + theme_minimal() + labs(title = "Calibration plot")
"""),
"residual": ([], "gg", """
p <- ggplot(df, aes(Fitted, Residual)) + geom_point(size = 3, color = "#2563eb") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#d8572a") +
  theme_minimal() + labs(title = "Residual plot")
"""),
"volcano": ([], "gg", """
df$sig <- ifelse(df$pValue < .05 & abs(df$log2FC) >= 1, ifelse(df$log2FC > 0, "Up", "Down"), "NS")
p <- ggplot(df, aes(log2FC, -log10(pValue), color = sig)) + geom_point(size = 2) +
  geom_hline(yintercept = -log10(.05), linetype = "dashed") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  scale_color_manual(values = c(Up = "#d8572a", Down = "#2563eb", NS = "grey")) +
  theme_minimal() + labs(title = "Volcano plot")
"""),
"ma_plot": ([], "gg", """
p <- ggplot(df, aes(Mean, log2FC, color = abs(log2FC) >= 1)) + geom_point(size = 2) +
  geom_hline(yintercept = 0) + scale_x_log10() +
  scale_color_manual(values = c("grey", "#d8572a"), guide = "none") +
  theme_minimal() + labs(title = "MA plot")
"""),
"manhattan": (["qqman"], "base", """
dd <- data.frame(SNP = paste0("s", seq_len(nrow(df))),
                 CHR = as.integer(factor(df$Chr)), BP = df$Position, P = df$pValue)
manhattan(dd, main = "Manhattan plot")
"""),
"clustered_heatmap": (["pheatmap"], "self", """
mat <- as.matrix(df[sapply(df, is.numeric)])
rownames(mat) <- df[[1]]
pheatmap(mat, main = "Clustered heatmap", filename = "jarvis_clustered_heatmap.png")
"""),
"pca": ([], "gg", """
num <- df[sapply(df, is.numeric)]
pc <- prcomp(num, scale. = TRUE)
sc <- as.data.frame(pc$x)
if ("Group" %in% names(df)) sc$Group <- df$Group
ev <- round(summary(pc)$importance[2, 1:2] * 100, 1)
p <- ggplot(sc, aes(PC1, PC2)) +
  { if ("Group" %in% names(df)) geom_point(aes(color = Group), size = 3) else geom_point(size = 3, color = "#2563eb") } +
  theme_minimal() + labs(title = "PCA", x = paste0("PC1 (", ev[1], "%)"), y = paste0("PC2 (", ev[2], "%)"))
"""),
"dose_response": (["drc"], "base", """
mod <- drm(Response ~ Dose, data = df, fct = LL.4())
plot(mod, main = "Dose-response (4PL)")
"""),
"bland_altman": ([], "gg", """
df$mean <- (df$MethodA + df$MethodB) / 2; df$diff <- df$MethodA - df$MethodB
md <- mean(df$diff); sdd <- sd(df$diff)
p <- ggplot(df, aes(mean, diff)) + geom_point(size = 3, color = "#2563eb") +
  geom_hline(yintercept = md, color = "#d8572a") +
  geom_hline(yintercept = c(md - 1.96 * sdd, md + 1.96 * sdd), linetype = "dashed") +
  theme_minimal() + labs(title = "Bland-Altman", x = "Mean of methods", y = "Difference")
"""),
"waterfall": ([], "gg", """
p <- ggplot(df, aes(reorder(Subject, -PctChange), PctChange, fill = PctChange < 0)) +
  geom_col() + geom_hline(yintercept = 0) +
  scale_fill_manual(values = c("FALSE" = "#d8572a", "TRUE" = "#1d9e75"), guide = "none") +
  theme_minimal() + theme(axis.text.x = element_blank()) + labs(title = "Waterfall", x = "Patients", y = "% change")
"""),
# --- 7. study-flow ---
"prisma": (["DiagrammeR"], "self", """
# PRISMA 2020 flow (databases & registers) rebuilt from the Field / Count table.
gv <- function(cands){for(nm in cands){v<-df$Count[tolower(trimws(df$Field))==tolower(nm)]; if(length(v)) return(v[1])}; 0}
rx <- df[grepl('^reason|^excluded:', tolower(trimws(as.character(df$Field)))), ]
rlab <- if (nrow(rx)) paste(paste0(sub('^[^:]*:\\\\s*','',rx$Field),' (n = ',rx$Count,')'), collapse='\\\\n') else 'None'
sx <- df[grepl('^source:|^database:|^register:', tolower(trimws(as.character(df$Field)))), ]
alab <- if (nrow(sx)) paste(paste0(sub('^[^:]*:\\\\s*','',sx$Field),' (n = ',sx$Count,')'), collapse='\\\\n') else paste0('Databases (n = ', gv(c('databases')), ')\\\\nRegisters (n = ', gv(c('registers')), ')')
library(DiagrammeR)
dot <- paste0("digraph prisma { graph [layout=dot, rankdir=TB, fontname=Helvetica] node [shape=box, style=filled, fillcolor=white, fontname=Helvetica] ",
"a  [label='Records identified from:\\\\n", alab, "'] ",
"a2 [label='Records removed before screening:\\\\nDuplicates (n = ", gv(c('duplicates removed','duplicates')), ")\\\\nAutomation-ineligible (n = ", gv(c('automation ineligible','automation-ineligible')), ")\\\\nOther (n = ", gv(c('other removed','other reasons')), ")'] ",
"b  [label='Records screened (n = ", gv(c('records screened','screened')), ")'] ",
"b2 [label='Records excluded (n = ", gv(c('records excluded')), ")'] ",
"c  [label='Reports sought for retrieval (n = ", gv(c('reports sought','reports sought for retrieval')), ")'] ",
"c2 [label='Reports not retrieved (n = ", gv(c('reports not retrieved','not retrieved')), ")'] ",
"d  [label='Reports assessed for eligibility (n = ", gv(c('reports assessed','reports assessed for eligibility')), ")'] ",
"d2 [label='Reports excluded:\\\\n", rlab, "'] ",
"e  [label='Studies included (n = ", gv(c('studies included','studies included in review')), ")\\\\nReports of included studies (n = ", gv(c('reports included','reports of included studies')), ")'] ",
"a->b b->c c->d d->e a->a2 b->b2 c->c2 d->d2 ",
"{rank=same; a a2} {rank=same; b b2} {rank=same; c c2} {rank=same; d d2} }")
grViz(dot)
"""),
"consort": (["DiagrammeR"], "self", """
nodes <- paste0('n', seq_len(nrow(df)), ' [label="', df$Stage, ' (n=', df$Count, ')", shape=box, style=rounded]')
edges <- if (nrow(df) > 1) paste0('n', seq_len(nrow(df) - 1), ' -> n', 2:nrow(df), collapse = '; ') else ''
grViz(paste0('digraph { rankdir=TB; ', paste(nodes, collapse = '; '), '; ', edges, ' }'))
"""),
"rob_traffic": ([], "gg", """
# robvis / QUADAS-2 style traffic-light plot. (For RoB2 you can also use the
# dedicated 'robvis' package: install.packages('robvis'); robvis::rob_traffic_light().)
lv <- tolower(df$Judgement)
df$Level <- ifelse(grepl("low", lv), "Low",
             ifelse(grepl("high|serious|critical", lv), "High", "Unclear"))
df$Level <- factor(df$Level, levels = c("Low", "Unclear", "High"))
df$Study <- factor(df$Study, levels = rev(unique(df$Study)))
df$Domain <- factor(df$Domain, levels = unique(df$Domain))
p <- ggplot(df, aes(Domain, Study)) +
  geom_tile(fill = "white", color = "black", linewidth = 0.4) +
  geom_point(aes(color = Level), size = 8) +
  scale_color_manual(values = c(Low = "#4cae4f", Unclear = "#f5c518", High = "#e63329"), drop = FALSE) +
  { if ("Panel" %in% names(df)) facet_grid(~ Panel, scales = "free_x", space = "free_x") else NULL } +
  scale_x_discrete(position = "top") +
  coord_equal() +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0, vjust = 0.5),
        panel.grid = element_blank(), axis.title = element_blank(),
        strip.text = element_text(face = "bold", size = 13)) +
  labs(color = "")
"""),
"gantt": ([], "gg", """
df$Start <- as.Date(df$Start); df$End <- as.Date(df$End)
p <- ggplot(df, aes(y = reorder(Task, -as.numeric(Start)))) +
  geom_segment(aes(x = Start, xend = End, yend = Task), linewidth = 6, color = "#2563eb") +
  theme_minimal() + labs(title = "Gantt / timeline", x = "Time", y = "Task")
"""),
# --- 8. meta-analysis (metafor / mada) ---
"forest_meta": (["metafor"], "base", """
if (!("SE" %in% names(df)) || all(is.na(df$SE))) df$SE <- (df$UpperCI - df$LowerCI) / (2 * 1.959964)
res <- rma(yi = df$Effect, sei = df$SE, method = "REML")
print(summary(res)); forest(res, slab = df$Study, header = TRUE, addpred = TRUE)
"""),
"funnel_meta": (["metafor"], "base", """
if (!("SE" %in% names(df)) || all(is.na(df$SE))) df$SE <- (df$UpperCI - df$LowerCI) / (2 * 1.959964)
res <- rma(yi = df$Effect, sei = df$SE, method = "REML")
funnel(res, level = c(90, 95, 99), shade = c("white", "gray55", "gray75"), legend = TRUE)
regtest(res)   # Egger's test
"""),
"radial_meta": (["metafor"], "base", """
if (!("SE" %in% names(df)) || all(is.na(df$SE))) df$SE <- (df$UpperCI - df$LowerCI) / (2 * 1.959964)
radial(rma(yi = df$Effect, sei = df$SE, method = "REML"))
"""),
"baujat_meta": (["metafor"], "base", """
if (!("SE" %in% names(df)) || all(is.na(df$SE))) df$SE <- (df$UpperCI - df$LowerCI) / (2 * 1.959964)
baujat(rma(yi = df$Effect, sei = df$SE, method = "REML"))
"""),
"loo_meta": (["metafor"], "base", """
if (!("SE" %in% names(df)) || all(is.na(df$SE))) df$SE <- (df$UpperCI - df$LowerCI) / (2 * 1.959964)
res <- rma(yi = df$Effect, sei = df$SE, method = "REML")
l <- leave1out(res)
forest(l$estimate, sei = l$se, slab = paste("Omitting", df$Study), header = TRUE)
"""),
"cumul_meta": (["metafor"], "base", """
if (!("SE" %in% names(df)) || all(is.na(df$SE))) df$SE <- (df$UpperCI - df$LowerCI) / (2 * 1.959964)
o <- order(df$Year)
res <- rma(yi = df$Effect[o], sei = df$SE[o], method = "REML")
forest(cumul(res, order = df$Year[o]), slab = df$Study[o], header = TRUE)
"""),
"labbe_meta": (["metafor"], "base", """
res <- rma(measure = "OR", ai = df$Events1, n1i = df$N1, ci = df$Events2, n2i = df$N2, data = df, method = "REML")
labbe(res, xlab = "Control arm", ylab = "Treatment arm")
"""),
"sroc_meta": (["mada"], "base", """
dm <- data.frame(TP = df$TP, FP = df$FP, FN = df$FN, TN = df$TN)
fit <- reitsma(dm, correction = 0.5, correction.control = "all"); print(summary(fit))
plot(fit, sroclwd = 2, xlim = c(0, 1), ylim = c(0, 1), main = "SROC (bivariate/HSROC)")
ROCellipse(fit, add = TRUE, col = "firebrick")
"""),
"deeks_meta": (["mada"], "base", """
dm <- data.frame(TP = df$TP, FP = df$FP, FN = df$FN, TN = df$TN)
# Deeks' funnel-plot asymmetry test (effective sample size vs 1/DOR)
ess <- with(dm, (TP+FN)*(FP+TN)/((TP+FN)+(FP+TN)))
dor <- with(dm, (TP*TN)/(FP*FN)); dor[!is.finite(dor)] <- NA
plot(1/sqrt(ess), log(dor), pch = 19, xlab = "1/sqrt(ESS)", ylab = "ln(DOR)", main = "Deeks' funnel")
abline(lm(log(dor) ~ I(1/sqrt(ess))), col = "firebrick")
"""),
}


def plot_r_script(spec, df, opt=None) -> str:
    entry = PLOT_R.get(spec.id)
    out = f"jarvis_{spec.id}.png"
    if entry is None:
        return _header(f"Plot — {spec.name}", []) + "\n# (R script not available for this plot)\n"
    packages, kind, code = entry
    pkgs = list(packages)
    if kind == "gg":
        pkgs = ["ggplot2"] + pkgs
    parts = [_header(f"Plot — {spec.name}", pkgs), df_to_r(canon_df(df, spec)), ""]
    code = code.strip()
    if kind == "gg":
        body = code + f'\n\nprint(p)\nggsave("{out}", p, width = 8, height = 5, dpi = 300)\n'
    elif kind == "base":
        body = f'png("{out}", width = 1800, height = 1100, res = 200)\n{code}\ndev.off()\n'
    else:  # self
        body = code + "\n"
    parts.append(body)
    return "\n".join(parts)
